name: CI/CD Pipeline Packify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packify-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './packify-frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit
        timeout-minutes: 10

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          NEXT_TELEMETRY_DISABLED: 1

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/packify-app:latest
            ${{ secrets.DOCKER_USERNAME }}/packify-app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: docker-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/packify
            
            # Vérifier que docker-compose.yml existe
            if [ ! -f docker-compose.yml ]; then
              echo "Error: docker-compose.yml not found"
              exit 1
            fi
            
            # Télécharger la nouvelle image
            docker pull ${{ secrets.DOCKER_USERNAME }}/packify-app:latest
            
            # Arrêter les services existants
            docker-compose down || true
            
            # Redémarrer avec la nouvelle image
            docker-compose up -d
            
            # Attendre que les services soient prêts
            sleep 30
            
            # Vérifier que les services sont en cours d'exécution
            docker-compose ps
            
            # Nettoyer les anciennes images
            docker image prune -f